"use client";

import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Update task",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-red">
      <Suspense>{children}</Suspense>
      <Toaster />
    </div>
  );
}
